name: Slack post release

on:
  release:
    types: [published]

permissions: {}

jobs:
  notify:
    uses: 0xMiden/.github/.github/workflows/slack-post-release.yml@main
    with:
      title: ${{ format('{0} {1}', github.event.repository.name, github.event.release.tag_name) }}
      release_url: ${{ github.event.release.html_url }}
      release_notes: ${{ github.event.release.body }}
    secrets:
      slack_webhook_url: ${{ secrets.RELEASE_SUMMARY_SLACK_WEBHOOK_URL }}
