# Runs changelog related jobs.
# CI job heavily inspired by: https://github.com/tarides/changelog-check-action

name: changelog

on:
  workflow_call:
    inputs:
      changelog_path:
        description: 'The CHANGELOG path'
        required: false
        type: string
        default: 'CHANGELOG.md'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout flows repo
      - uses: actions/checkout@v4
        with:
          repository: atsaero/.github
          ref: feature-reusable-flows
      - name: Check for changes in changelog
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          NO_CHANGELOG_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'no changelog') }}
        run: ./scripts/check-changelog.sh "${{ inputs.changelog_path }}"
        shell: bash
