name: Publish Docker Image

on:
  workflow_call:
    inputs:
      component:
        description: 'The component to build a Docker image for'
        required: true
        type: string

      dockerfile_path:
        description: 'The Dockerfile path for the component'
        required: false
        type: string
        default: 'Dockerfile'

      registry:
        description: "Docker registry"
        required: false
        type: string
        default: 'ghcr.io'

      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string
    
    secrets:
      gh_token:
        description: 'Github token'
        required: true

      aws_region:
        description: 'AWS region'
        required: true

      aws_role:
        description: 'AWS role'
        required: true

      aws_cache_bucket:
        description: 'AWS cache bucket'
        required: true

jobs:
  publish:
    runs-on:
      labels: "ubuntu-latest"
    name: Publish ${{ inputs.component }} ${{ inputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.gh_token }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.aws_region }}
          role-to-assume: ${{ secrets.aws_role }}
          role-session-name: GithubActionsSession

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache-binary: true

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ inputs.dockerfile_path }}
          tags: ${{ inputs.registry }}/0xmiden/miden-${{ inputs.component }}:${{ inputs.version }}
          cache-from: type=s3,region=${{ secrets.aws_region }},bucket=${{ secrets.aws_cache_bucket }},name=miden-${{ inputs.component }}
          cache-to: type=s3,region=${{ secrets.aws_region }},bucket=${{ secrets.aws_cache_bucket }},name=miden-${{ inputs.component }},mode=max
